Show org and space quotas
cloudfoundry/cli pull request #2299
Opened 2022-07-20 23:49 UTC by mkocher

This is blocked on #2298, don't merge before then.

Adds log volume limits to quota displays.

/cc @ctlong

2022-07-21 20:36 UTC, ctlong requested changes

2022-07-21 20:36 UTC, ctlong commented on integration/v7/isolated/create_org_quota_command_test.go
> +					//TODO: add an assertion for log quota information
Replace this TODO with an assertion.

2022-07-21 20:36 UTC, ctlong commented on integration/v7/isolated/create_org_quota_command_test.go
> +					//TODO: add an assertion for log quota information
Replace this TODO with an assertion.

2022-07-21 20:36 UTC, ctlong commented on integration/v7/isolated/update_org_quota_command_test.go
> +			//TODO: add an assertion for log quota information
Replace this TODO with an assertion.

2022-07-25 23:30 UTC, ctlong commented
This updates four commands:

* `org-quotas`
* `org-quota`
* `space-quotas`
* `space-quota`

2022-07-26 02:24 UTC, pivotalgeorge commented
Cool, this looks good in that it builds and displays org quotas with `unlimited` by default.
However, just noticed that when I run `<cf> create-org-quota` the help output includes `[-l LOG_VOLUME]`, but the `<cf> create-space-quota` command does not include this flag. This might be more of a #2298 issue, though, so not blocking merge of #2299 on this.

2022-07-26 14:43 UTC, ctlong commented
@pivotalgeorge the work to add the `-l` flag for `create-space-quota` and `update-space-quota` can be found in #2300. This PR is only focused on the "read" commands, and #2298 was only focused on the org-level "write" commands.

Our goal in splitting up the work like this is to make each PR more easily reviewable by y'all. Happy to take feedback (ideally in slack) to improve our current process, if you're having problems with it :).

2022-07-26 18:46 UTC, pivotalgeorge commented
@ctlong no that makes sense, I just thought I remembered seeing changes to both space and org quota commands in #2298

2022-07-26 20:39 UTC, jdgonzaleza approved these changes
LGTM

2022-07-26 20:39 UTC, merged