Ensure response body is always closed in CloudControllerConnection
cloudfoundry/cli pull request #2423
Opened 2023-05-18 14:47 UTC by chitoku-k

## Does this PR modify CLI v6, CLI v7, or CLI v8?

CLI v8

## Description of the Change

This PR ensures that a response body returned from `HTTPClient` in `CloudControllerConnection.Make()` is correctly closed in all of the following circumstances:
* when the status code of the response is `http.StatusNoContent`
* when the handling of `X-Cf-Warnings` returns an error

## Why Is This PR Valuable?

Some projects import cloudfoundry/cli as a means to interact with CAPI and they should benefit from this fix.

## Why Should This Be In Core?

N/A

## Applicable Issues

N/A

## How Urgent Is The Change?

There should be a few projects that are currently affected by this bug such as [bosh-prometheus/cf_exporter](https://github.com/bosh-prometheus/cf_exporter).

## Other Relevant Parties

None.

2023-05-18 16:08 UTC, a-b approved these changes
lgtm

2023-05-18 16:10 UTC, a-b commented
Please create PRs for:
- [ ] [main](https://github.com/cloudfoundry/cli/tree/main)
- [ ] [v7](https://github.com/cloudfoundry/cli/tree/v7)

2023-05-18 16:15 UTC, chitoku-k commented
Thank you for the prompt response. I've created #2424 and #2425, for v7 and v8 branch respectively.

2024-01-09 22:46 UTC, a-b requested changes
Per additional review with @moleske , @ccjaimes we recommending moving `defer` even closer to where we opening connection [here](https://github.com/cloudfoundry/cli/blob/8415e6bcab12425bb9e15e7695c321ff550b519a/api/cloudcontroller/cloud_controller_connection.go#L58)

2024-01-10 02:27 UTC, chitoku-k commented
Thanks, I have modified the commit in this and the other two PRs that way.

2024-01-11 19:30 UTC, ccjaimes commented
@chitoku-k Thanks for your fast response on these changes. Merging these PRs now.

2024-01-11 19:31 UTC, ccjaimes approved these changes

2024-01-16 18:06 UTC, a-b approved these changes

2024-01-18 18:03 UTC, merged