RFC0027 CLI command "update-route" to manage generic per-route options
cloudfoundry/cli pull request #3338
Opened 2024-12-19 13:27 UTC by Dariquest

## CLI Support for Generic Per-Route Options 

Introducing a new cli command 'update-route', which allows updates to route resources. 
Extending the API of the Route to contain generic options map.

Detailed specification including that of for all the involved components is provided in the [RFC](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0027-generic-per-route-features.md)

```
$ cf update-route -h
NAME:
   update-route - Update an existing route.

USAGE:
   cf update-route DOMAIN [--hostname HOSTNAME] [--path PATH] [--option OPTION=VALUE] [--remove-option OPTION]

EXAMPLES:
   cf update-route example.com -o loadbalancing=round-robin
   cf update-route example.com -o loadbalancing=least-connection
   cf update-route example.com -r loadbalancing

OPTIONS:
   --hostname, -n      Hostname for the HTTP route (required for shared domains)
   --path              Path for the HTTP route
   --option -o         Set the value of a per-route option, key-value pairs, repeat to set multiple options
   --remove-option -r  Unset a previously set option

SEE ALSO:
   create-route, map-route, routes, unmap-route
```
It should be possible to provide options in the create-route and map-route commands.

```
EXAMPLES:
  cf create-route my-space example.com -o loadbalancing=round-robin
  cf map-route my-app example.com -o loadbalancing=least-connection
```

## Why Is This PR Valuable?

Allow users to manage per-route options via the CLI instead of having to talk to the API directly. 

## Applicable Issues

[GitHub Issue](https://github.com/cloudfoundry/cli/issues/3314)

## How Urgent Is The Change?

No urgency

2025-01-09 15:50 UTC, MarcPaquette commented
FYI @gururajsh

2025-01-10 16:58 UTC, a-b requested changes
Thank you for your contribution. However, we do not make changes in the `cf` folder because it predates version 6 and is marked as deprecated. We hope to remove it soon, as plugins are the only reason it remains in the code.

2025-01-10 17:01 UTC, a-b commented
Also, we noticed that you've made your original request against the `main` branch - as it should be, but later [closed](https://github.com/cloudfoundry/cli/pull/3328#issuecomment-2554275438). What was your motivation for this change?

2025-01-13 07:46 UTC, Dariquest commented
> Also, we noticed that you've made your original request against the `main` branch - as it should be, but later [closed](https://github.com/cloudfoundry/cli/pull/3328#issuecomment-2554275438). What was your motivation for this change?

Hi @a-b, I was advised in the cli channel, that I should develop against the version branches. The new command is intended for the v8 and not for the v9 (as far as I understood from the contribution guide, main will become v9 later, and v8 is the target version if I intend to add a v8 command). Have I got it wrong?

2025-02-18 16:31 UTC, Dariquest commented
A new PR was created to leave the command folder untouched https://github.com/cloudfoundry/cli/pull/3366

2025-02-18 16:31 UTC, closed without merging